<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Types\BuiltInTypesMessage;

use UnexpectedValueException;

/**
 * Protobuf type <code>types.BuiltInTypesMessage.MessageLevelEnum</code>
 */
class MessageLevelEnum
{
    /**
     * Generated from protobuf enum <code>MSG_A = 0;</code>
     */
    const MSG_A = 0;
    /**
     * Generated from protobuf enum <code>MSG_B = 1;</code>
     */
    const MSG_B = 1;
    /**
     * Generated from protobuf enum <code>MSG_C = 77;</code>
     */
    const MSG_C = 77;

    private static $valueToName = [
        self::MSG_A => 'MSG_A',
        self::MSG_B => 'MSG_B',
        self::MSG_C => 'MSG_C',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MessageLevelEnum::class, \Types\BuiltInTypesMessage_MessageLevelEnum::class);

