<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.BuiltInTypesMessage</code>
 */
class BuiltInTypesMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes bytes_field = 1;</code>
     */
    private $bytes_field = '';
    /**
     * Generated from protobuf field <code>string string_field = 2;</code>
     */
    private $string_field = '';
    /**
     * Generated from protobuf field <code>int32 int32_field = 3;</code>
     */
    private $int32_field = 0;
    /**
     * Generated from protobuf field <code>uint32 uint32_field = 4;</code>
     */
    private $uint32_field = 0;
    /**
     * Generated from protobuf field <code>int64 int64_field = 5;</code>
     */
    private $int64_field = 0;
    /**
     * Generated from protobuf field <code>uint64 uint64_field = 6;</code>
     */
    private $uint64_field = 0;
    /**
     * Generated from protobuf field <code>bool bool_field = 7;</code>
     */
    private $bool_field = false;
    /**
     * Generated from protobuf field <code>double double_field = 8;</code>
     */
    private $double_field = 0.0;
    /**
     * Generated from protobuf field <code>float float_field = 9;</code>
     */
    private $float_field = 0.0;
    /**
     * Generated from protobuf field <code>map<string, int32> map_field = 10;</code>
     */
    private $map_field;
    /**
     * Generated from protobuf field <code>map<int32, .types.BuiltInTypesMessage> other_map_field = 12;</code>
     */
    private $other_map_field;
    /**
     * Generated from protobuf field <code>repeated string repeated_strings_field = 20;</code>
     */
    private $repeated_strings_field;
    /**
     * Generated from protobuf field <code>repeated int32 repeated_int32_field = 21;</code>
     */
    private $repeated_int32_field;
    /**
     * Generated from protobuf field <code>repeated bool repeated_bool_field = 22;</code>
     */
    private $repeated_bool_field;
    /**
     * Generated from protobuf field <code>.types.PackageLevelEnum pkg_enum_field = 30;</code>
     */
    private $pkg_enum_field = 0;
    /**
     * Generated from protobuf field <code>.types.BuiltInTypesMessage.MessageLevelEnum msg_enum_field = 31;</code>
     */
    private $msg_enum_field = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bytes_field
     *     @type string $string_field
     *     @type int $int32_field
     *     @type int $uint32_field
     *     @type int|string $int64_field
     *     @type int|string $uint64_field
     *     @type bool $bool_field
     *     @type float $double_field
     *     @type float $float_field
     *     @type array|\Google\Protobuf\Internal\MapField $map_field
     *     @type array|\Google\Protobuf\Internal\MapField $other_map_field
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $repeated_strings_field
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $repeated_int32_field
     *     @type bool[]|\Google\Protobuf\Internal\RepeatedField $repeated_bool_field
     *     @type int $pkg_enum_field
     *     @type int $msg_enum_field
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes bytes_field = 1;</code>
     * @return string
     */
    public function getBytesField()
    {
        return $this->bytes_field;
    }

    /**
     * Generated from protobuf field <code>bytes bytes_field = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBytesField($var)
    {
        GPBUtil::checkString($var, False);
        $this->bytes_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_field = 2;</code>
     * @return string
     */
    public function getStringField()
    {
        return $this->string_field;
    }

    /**
     * Generated from protobuf field <code>string string_field = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStringField($var)
    {
        GPBUtil::checkString($var, True);
        $this->string_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 int32_field = 3;</code>
     * @return int
     */
    public function getInt32Field()
    {
        return $this->int32_field;
    }

    /**
     * Generated from protobuf field <code>int32 int32_field = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setInt32Field($var)
    {
        GPBUtil::checkInt32($var);
        $this->int32_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 uint32_field = 4;</code>
     * @return int
     */
    public function getUint32Field()
    {
        return $this->uint32_field;
    }

    /**
     * Generated from protobuf field <code>uint32 uint32_field = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUint32Field($var)
    {
        GPBUtil::checkUint32($var);
        $this->uint32_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int64_field = 5;</code>
     * @return int|string
     */
    public function getInt64Field()
    {
        return $this->int64_field;
    }

    /**
     * Generated from protobuf field <code>int64 int64_field = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInt64Field($var)
    {
        GPBUtil::checkInt64($var);
        $this->int64_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 uint64_field = 6;</code>
     * @return int|string
     */
    public function getUint64Field()
    {
        return $this->uint64_field;
    }

    /**
     * Generated from protobuf field <code>uint64 uint64_field = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUint64Field($var)
    {
        GPBUtil::checkUint64($var);
        $this->uint64_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_field = 7;</code>
     * @return bool
     */
    public function getBoolField()
    {
        return $this->bool_field;
    }

    /**
     * Generated from protobuf field <code>bool bool_field = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolField($var)
    {
        GPBUtil::checkBool($var);
        $this->bool_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_field = 8;</code>
     * @return float
     */
    public function getDoubleField()
    {
        return $this->double_field;
    }

    /**
     * Generated from protobuf field <code>double double_field = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleField($var)
    {
        GPBUtil::checkDouble($var);
        $this->double_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float float_field = 9;</code>
     * @return float
     */
    public function getFloatField()
    {
        return $this->float_field;
    }

    /**
     * Generated from protobuf field <code>float float_field = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatField($var)
    {
        GPBUtil::checkFloat($var);
        $this->float_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> map_field = 10;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMapField()
    {
        return $this->map_field;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> map_field = 10;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMapField($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->map_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, .types.BuiltInTypesMessage> other_map_field = 12;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOtherMapField()
    {
        return $this->other_map_field;
    }

    /**
     * Generated from protobuf field <code>map<int32, .types.BuiltInTypesMessage> other_map_field = 12;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOtherMapField($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\BuiltInTypesMessage::class);
        $this->other_map_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string repeated_strings_field = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRepeatedStringsField()
    {
        return $this->repeated_strings_field;
    }

    /**
     * Generated from protobuf field <code>repeated string repeated_strings_field = 20;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRepeatedStringsField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->repeated_strings_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 repeated_int32_field = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRepeatedInt32Field()
    {
        return $this->repeated_int32_field;
    }

    /**
     * Generated from protobuf field <code>repeated int32 repeated_int32_field = 21;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRepeatedInt32Field($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->repeated_int32_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bool repeated_bool_field = 22;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRepeatedBoolField()
    {
        return $this->repeated_bool_field;
    }

    /**
     * Generated from protobuf field <code>repeated bool repeated_bool_field = 22;</code>
     * @param bool[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRepeatedBoolField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->repeated_bool_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.PackageLevelEnum pkg_enum_field = 30;</code>
     * @return int
     */
    public function getPkgEnumField()
    {
        return $this->pkg_enum_field;
    }

    /**
     * Generated from protobuf field <code>.types.PackageLevelEnum pkg_enum_field = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setPkgEnumField($var)
    {
        GPBUtil::checkEnum($var, \Types\PackageLevelEnum::class);
        $this->pkg_enum_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.BuiltInTypesMessage.MessageLevelEnum msg_enum_field = 31;</code>
     * @return int
     */
    public function getMsgEnumField()
    {
        return $this->msg_enum_field;
    }

    /**
     * Generated from protobuf field <code>.types.BuiltInTypesMessage.MessageLevelEnum msg_enum_field = 31;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgEnumField($var)
    {
        GPBUtil::checkEnum($var, \Types\BuiltInTypesMessage_MessageLevelEnum::class);
        $this->msg_enum_field = $var;

        return $this;
    }

}

