<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Types;

if (false) {
    /**
     * This class is deprecated. Use Types\BuiltInTypesMessage\MessageLevelEnum instead.
     * @deprecated
     */
    class BuiltInTypesMessage_MessageLevelEnum {}
}
class_exists(BuiltInTypesMessage\MessageLevelEnum::class);
@trigger_error('Types\BuiltInTypesMessage_MessageLevelEnum is deprecated and will be removed in the next major release. Use Types\BuiltInTypesMessage\MessageLevelEnum instead', E_USER_DEPRECATED);

