<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.WellKnownTypesMessage</code>
 */
class WellKnownTypesMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Any any_field = 1;</code>
     */
    private $any_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration duration_field = 3;</code>
     */
    private $duration_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Empty empty_field = 4;</code>
     */
    private $empty_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct struct_field = 7;</code>
     */
    private $struct_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp_field = 8;</code>
     */
    private $timestamp_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.DoubleValue double_field = 10;</code>
     */
    private $double_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.FloatValue float_field = 11;</code>
     */
    private $float_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int64Value int64_field = 12;</code>
     */
    private $int64_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.UInt64Value uint64_field = 13;</code>
     */
    private $uint64_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value int32_field = 14;</code>
     */
    private $int32_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value uint32_field = 15;</code>
     */
    private $uint32_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue bool_field = 16;</code>
     */
    private $bool_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue string_field = 17;</code>
     */
    private $string_field = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BytesValue bytes_field = 18;</code>
     */
    private $bytes_field = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Any $any_field
     *     @type \Google\Protobuf\Duration $duration_field
     *     @type \Google\Protobuf\GPBEmpty $empty_field
     *     @type \Google\Protobuf\Struct $struct_field
     *     @type \Google\Protobuf\Timestamp $timestamp_field
     *     @type \Google\Protobuf\DoubleValue $double_field
     *     @type \Google\Protobuf\FloatValue $float_field
     *     @type \Google\Protobuf\Int64Value $int64_field
     *     @type \Google\Protobuf\UInt64Value $uint64_field
     *     @type \Google\Protobuf\Int32Value $int32_field
     *     @type \Google\Protobuf\UInt32Value $uint32_field
     *     @type \Google\Protobuf\BoolValue $bool_field
     *     @type \Google\Protobuf\StringValue $string_field
     *     @type \Google\Protobuf\BytesValue $bytes_field
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any any_field = 1;</code>
     * @return \Google\Protobuf\Any
     */
    public function getAnyField()
    {
        return $this->any_field;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any any_field = 1;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setAnyField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->any_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration duration_field = 3;</code>
     * @return \Google\Protobuf\Duration
     */
    public function getDurationField()
    {
        return $this->duration_field;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration duration_field = 3;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setDurationField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->duration_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty empty_field = 4;</code>
     * @return \Google\Protobuf\GPBEmpty
     */
    public function getEmptyField()
    {
        return $this->empty_field;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty empty_field = 4;</code>
     * @param \Google\Protobuf\GPBEmpty $var
     * @return $this
     */
    public function setEmptyField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\GPBEmpty::class);
        $this->empty_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct struct_field = 7;</code>
     * @return \Google\Protobuf\Struct
     */
    public function getStructField()
    {
        return $this->struct_field;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct struct_field = 7;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setStructField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->struct_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp_field = 8;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getTimestampField()
    {
        return $this->timestamp_field;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp_field = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestampField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.DoubleValue double_field = 10;</code>
     * @return \Google\Protobuf\DoubleValue
     */
    public function getDoubleField()
    {
        return $this->double_field;
    }

    /**
     * Returns the unboxed value from <code>getDoubleField()</code>

     * Generated from protobuf field <code>.google.protobuf.DoubleValue double_field = 10;</code>
     * @return float|null
     */
    public function getDoubleFieldUnwrapped()
    {
        $wrapper = $this->getDoubleField();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.DoubleValue double_field = 10;</code>
     * @param \Google\Protobuf\DoubleValue $var
     * @return $this
     */
    public function setDoubleField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\DoubleValue::class);
        $this->double_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\DoubleValue object.

     * Generated from protobuf field <code>.google.protobuf.DoubleValue double_field = 10;</code>
     * @param float|null $var
     * @return $this
     */
    public function setDoubleFieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\DoubleValue(['value' => $var]);
        return $this->setDoubleField($wrappedVar);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.FloatValue float_field = 11;</code>
     * @return \Google\Protobuf\FloatValue
     */
    public function getFloatField()
    {
        return $this->float_field;
    }

    /**
     * Returns the unboxed value from <code>getFloatField()</code>

     * Generated from protobuf field <code>.google.protobuf.FloatValue float_field = 11;</code>
     * @return float|null
     */
    public function getFloatFieldUnwrapped()
    {
        $wrapper = $this->getFloatField();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.FloatValue float_field = 11;</code>
     * @param \Google\Protobuf\FloatValue $var
     * @return $this
     */
    public function setFloatField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FloatValue::class);
        $this->float_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\FloatValue object.

     * Generated from protobuf field <code>.google.protobuf.FloatValue float_field = 11;</code>
     * @param float|null $var
     * @return $this
     */
    public function setFloatFieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\FloatValue(['value' => $var]);
        return $this->setFloatField($wrappedVar);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int64Value int64_field = 12;</code>
     * @return \Google\Protobuf\Int64Value
     */
    public function getInt64Field()
    {
        return $this->int64_field;
    }

    /**
     * Returns the unboxed value from <code>getInt64Field()</code>

     * Generated from protobuf field <code>.google.protobuf.Int64Value int64_field = 12;</code>
     * @return int|string|null
     */
    public function getInt64FieldUnwrapped()
    {
        $wrapper = $this->getInt64Field();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int64Value int64_field = 12;</code>
     * @param \Google\Protobuf\Int64Value $var
     * @return $this
     */
    public function setInt64Field($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int64Value::class);
        $this->int64_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int64Value object.

     * Generated from protobuf field <code>.google.protobuf.Int64Value int64_field = 12;</code>
     * @param int|string|null $var
     * @return $this
     */
    public function setInt64FieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\Int64Value(['value' => $var]);
        return $this->setInt64Field($wrappedVar);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt64Value uint64_field = 13;</code>
     * @return \Google\Protobuf\UInt64Value
     */
    public function getUint64Field()
    {
        return $this->uint64_field;
    }

    /**
     * Returns the unboxed value from <code>getUint64Field()</code>

     * Generated from protobuf field <code>.google.protobuf.UInt64Value uint64_field = 13;</code>
     * @return int|string|null
     */
    public function getUint64FieldUnwrapped()
    {
        $wrapper = $this->getUint64Field();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt64Value uint64_field = 13;</code>
     * @param \Google\Protobuf\UInt64Value $var
     * @return $this
     */
    public function setUint64Field($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt64Value::class);
        $this->uint64_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\UInt64Value object.

     * Generated from protobuf field <code>.google.protobuf.UInt64Value uint64_field = 13;</code>
     * @param int|string|null $var
     * @return $this
     */
    public function setUint64FieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\UInt64Value(['value' => $var]);
        return $this->setUint64Field($wrappedVar);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value int32_field = 14;</code>
     * @return \Google\Protobuf\Int32Value
     */
    public function getInt32Field()
    {
        return $this->int32_field;
    }

    /**
     * Returns the unboxed value from <code>getInt32Field()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value int32_field = 14;</code>
     * @return int|null
     */
    public function getInt32FieldUnwrapped()
    {
        $wrapper = $this->getInt32Field();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value int32_field = 14;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setInt32Field($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->int32_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value int32_field = 14;</code>
     * @param int|null $var
     * @return $this
     */
    public function setInt32FieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\Int32Value(['value' => $var]);
        return $this->setInt32Field($wrappedVar);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value uint32_field = 15;</code>
     * @return \Google\Protobuf\UInt32Value
     */
    public function getUint32Field()
    {
        return $this->uint32_field;
    }

    /**
     * Returns the unboxed value from <code>getUint32Field()</code>

     * Generated from protobuf field <code>.google.protobuf.UInt32Value uint32_field = 15;</code>
     * @return int|null
     */
    public function getUint32FieldUnwrapped()
    {
        $wrapper = $this->getUint32Field();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value uint32_field = 15;</code>
     * @param \Google\Protobuf\UInt32Value $var
     * @return $this
     */
    public function setUint32Field($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt32Value::class);
        $this->uint32_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\UInt32Value object.

     * Generated from protobuf field <code>.google.protobuf.UInt32Value uint32_field = 15;</code>
     * @param int|null $var
     * @return $this
     */
    public function setUint32FieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\UInt32Value(['value' => $var]);
        return $this->setUint32Field($wrappedVar);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue bool_field = 16;</code>
     * @return \Google\Protobuf\BoolValue
     */
    public function getBoolField()
    {
        return $this->bool_field;
    }

    /**
     * Returns the unboxed value from <code>getBoolField()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue bool_field = 16;</code>
     * @return bool|null
     */
    public function getBoolFieldUnwrapped()
    {
        $wrapper = $this->getBoolField();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue bool_field = 16;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setBoolField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->bool_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue bool_field = 16;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setBoolFieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\BoolValue(['value' => $var]);
        return $this->setBoolField($wrappedVar);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue string_field = 17;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getStringField()
    {
        return $this->string_field;
    }

    /**
     * Returns the unboxed value from <code>getStringField()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue string_field = 17;</code>
     * @return string|null
     */
    public function getStringFieldUnwrapped()
    {
        $wrapper = $this->getStringField();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue string_field = 17;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setStringField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->string_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue string_field = 17;</code>
     * @param string|null $var
     * @return $this
     */
    public function setStringFieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\StringValue(['value' => $var]);
        return $this->setStringField($wrappedVar);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BytesValue bytes_field = 18;</code>
     * @return \Google\Protobuf\BytesValue
     */
    public function getBytesField()
    {
        return $this->bytes_field;
    }

    /**
     * Returns the unboxed value from <code>getBytesField()</code>

     * Generated from protobuf field <code>.google.protobuf.BytesValue bytes_field = 18;</code>
     * @return string|null
     */
    public function getBytesFieldUnwrapped()
    {
        $wrapper = $this->getBytesField();
        return is_null($wrapper) ? null : $wrapper->getValue();
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BytesValue bytes_field = 18;</code>
     * @param \Google\Protobuf\BytesValue $var
     * @return $this
     */
    public function setBytesField($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BytesValue::class);
        $this->bytes_field = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BytesValue object.

     * Generated from protobuf field <code>.google.protobuf.BytesValue bytes_field = 18;</code>
     * @param string|null $var
     * @return $this
     */
    public function setBytesFieldUnwrapped($var)
    {
        $wrappedVar = is_null($var) ? null : new \Google\Protobuf\BytesValue(['value' => $var]);
        return $this->setBytesField($wrappedVar);
    }

}

