// <auto-generated>
//     Generated by the protocol buffer compiler plugin.  DO NOT EDIT!
//     source: greeter.proto
// </auto-generated>


using System.Threading;
using System.Threading.Tasks;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace Greeter
{

    /// <summary>
    /// This is just an example service that
    /// uses imports
    /// </summary>
    public interface IGreeterHttpClient
    {

		
        /// <summary>
        /// Simple hello method
        /// </summary>
         Task<global::Greeter.HelloResponse> Hello(global::Greeter.HelloRequest request, CancellationToken cancellationToken = default);
		


        /// <summary>
        /// Simple ext method
        /// </summary>
        [global::System.Obsolete]  Task<global::Ext.ExtResponse> Ext(global::Ext.ExtRequest request, CancellationToken cancellationToken = default);
		


        /// <summary>

        /// </summary>
         Task<global::Zett.ZettResponse> Zett(global::Zett.ZettRequest request, CancellationToken cancellationToken = default);
		


        /// <summary>

        /// </summary>
         Task<global::Zett.ZettResponse> Get(global::Google.Protobuf.WellKnownTypes.Int32Value request, CancellationToken cancellationToken = default);
		


    }
}
