<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ext.proto

namespace Ext;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ext.ExtResponse</code>
 */
class ExtResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string greeting = 2;</code>
     */
    private $greeting = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $greeting
     * }
     */
    public function __construct($data = NULL) {
        \Ext\Metadata\Ext::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string greeting = 2;</code>
     * @return string
     */
    public function getGreeting()
    {
        return $this->greeting;
    }

    /**
     * Generated from protobuf field <code>string greeting = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGreeting($var)
    {
        GPBUtil::checkString($var, True);
        $this->greeting = $var;

        return $this;
    }

}

