<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zett.proto

namespace Zett\Metadata;

class Zett
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7c0a0a7a6574742e70726f746f12047a657474221b0a0b5a6574745265" .
            "7175657374120c0a046e616d6518012001280922200a0c5a657474526573" .
            "706f6e736512100a086772656574696e671802200128094221aa02045a65" .
            "7474ca02045a657474d00201e2020d5a6574745c4d657461646174616206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

