<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ext.proto

namespace Ext\Metadata;

class Ext
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a750a096578742e70726f746f1203657874221a0a0a4578745265717565" .
            "7374120c0a046e616d65180120012809221f0a0b457874526573706f6e73" .
            "6512100a086772656574696e67180220012809421eaa0203457874ca0203" .
            "457874d00201e2020c4578745c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

