<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

namespace Example;

/**
 * This is just an example service that
 * uses imports
 *
 * Protobuf type <code>example.Greeter</code>
 */
interface GreeterInterface
{
    /**
     * Simple hello method
     *
     * Method <code>hello</code>
     *
     * @param \Example\HelloRequest $request
     * @return \Example\HelloResponse
     */
    public function hello(\Example\HelloRequest $request);

    /**
     * Simple ext method
     *
     * Method <code>ext</code>
     *
     * @param \Ext\ExtRequest $request
     * @return \Ext\ExtResponse
     */
    public function ext(\Ext\ExtRequest $request);

    /**
     * Method <code>zett</code>
     *
     * @param \Zett\ZettRequest $request
     * @return \Zett\ZettResponse
     */
    public function zett(\Zett\ZettRequest $request);

}

