<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

namespace Greeter\Metadata;

class Greeter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Ext\Metadata\Ext::initOnce();
        \Zett\Metadata\Zett::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95030a0d677265657465722e70726f746f1207677265657465721a0a7a" .
            "6574742e70726f746f1a1e676f6f676c652f70726f746f6275662f777261" .
            "70706572732e70726f746f221c0a0c48656c6c6f52657175657374120c0a" .
            "046e616d6518012001280922210a0d48656c6c6f526573706f6e73651210" .
            "0a086772656574696e6718022001280932d9010a07477265657465721238" .
            "0a0548656c6c6f12152e677265657465722e48656c6c6f52657175657374" .
            "1a162e677265657465722e48656c6c6f526573706f6e73652200122d0a03" .
            "457874120f2e6578742e457874526571756573741a102e6578742e457874" .
            "526573706f6e73652203880201122d0a045a65747412112e7a6574742e5a" .
            "657474526571756573741a122e7a6574742e5a657474526573706f6e7365" .
            "12360a03476574121b2e676f6f676c652e70726f746f6275662e496e7433" .
            "3256616c75651a122e7a6574742e5a657474526573706f6e7365422aaa02" .
            "0747726565746572ca020747726565746572d00201e20210477265657465" .
            "725c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

