<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

namespace Example\Metadata;

class Greeter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Ext\Metadata\Ext::initOnce();
        \Zett\Metadata\Zett::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd020a0d677265657465722e70726f746f12076578616d706c651a0a7a" .
            "6574742e70726f746f221c0a0c48656c6c6f52657175657374120c0a046e" .
            "616d6518012001280922210a0d48656c6c6f526573706f6e736512100a08" .
            "6772656574696e6718022001280932a1010a074772656574657212380a05" .
            "48656c6c6f12152e6578616d706c652e48656c6c6f526571756573741a16" .
            "2e6578616d706c652e48656c6c6f526573706f6e73652200122d0a034578" .
            "74120f2e6578742e457874526571756573741a102e6578742e4578745265" .
            "73706f6e73652203880201122d0a045a65747412112e7a6574742e5a6574" .
            "74526571756573741a122e7a6574742e5a657474526573706f6e7365422a" .
            "aa02074578616d706c65ca02074578616d706c65d00201e202104578616d" .
            "706c655c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

