<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

namespace Greeter;

/**
 * This is just an example service that
 * uses imports
 *
 * Protobuf type <code>greeter.Greeter</code>
 */
interface GreeterInterface
{
    /**
     * Simple hello method
     *
     * Method <code>hello</code>
     *
     * @param \Greeter\HelloRequest $request
     * @return \Greeter\HelloResponse
     */
    public function hello(\Greeter\HelloRequest $request);

    /**
     * Simple ext method
     *
     * Method <code>ext</code>
     *
     * @param \Ext\ExtRequest $request
     * @return \Ext\ExtResponse
     */
    public function ext(\Ext\ExtRequest $request);

    /**
     * Method <code>zett</code>
     *
     * @param \Zett\ZettRequest $request
     * @return \Zett\ZettResponse
     */
    public function zett(\Zett\ZettRequest $request);

    /**
     * Method <code>get</code>
     *
     * @param \Google\Protobuf\Int32Value $request
     * @return \Zett\ZettResponse
     */
    public function get(\Google\Protobuf\Int32Value $request);

}

