<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nested.proto

namespace Nested;

if (false) {
    /**
     * This class is deprecated. Use Nested\NestedOuter\NestedInner instead.
     * @deprecated
     */
    class NestedOuter_NestedInner {}
}
class_exists(NestedOuter\NestedInner::class);
@trigger_error('Nested\NestedOuter_NestedInner is deprecated and will be removed in the next major release. Use Nested\NestedOuter\NestedInner instead', E_USER_DEPRECATED);

