// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Types {

  /// <summary>Holder for reflection information generated from types.proto</summary>
  public static partial class TypesReflection {

    #region Descriptor
    /// <summary>File descriptor for types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt0eXBlcy5wcm90bxIFdHlwZXMaGWdvb2dsZS9wcm90b2J1Zi9hbnkucHJv",
            "dG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aHmdvb2dsZS9w",
            "cm90b2J1Zi9kdXJhdGlvbi5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5",
            "LnByb3RvGhxnb29nbGUvcHJvdG9idWYvc3RydWN0LnByb3RvGh5nb29nbGUv",
            "cHJvdG9idWYvd3JhcHBlcnMucHJvdG8i4wUKE0J1aWx0SW5UeXBlc01lc3Nh",
            "Z2USEwoLYnl0ZXNfZmllbGQYASABKAwSFAoMc3RyaW5nX2ZpZWxkGAIgASgJ",
            "EhMKC2ludDMyX2ZpZWxkGAMgASgFEhQKDHVpbnQzMl9maWVsZBgEIAEoDRIT",
            "CgtpbnQ2NF9maWVsZBgFIAEoAxIUCgx1aW50NjRfZmllbGQYBiABKAQSEgoK",
            "Ym9vbF9maWVsZBgHIAEoCBIUCgxkb3VibGVfZmllbGQYCCABKAESEwoLZmxv",
            "YXRfZmllbGQYCSABKAISOwoJbWFwX2ZpZWxkGAogAygLMigudHlwZXMuQnVp",
            "bHRJblR5cGVzTWVzc2FnZS5NYXBGaWVsZEVudHJ5EkYKD290aGVyX21hcF9m",
            "aWVsZBgMIAMoCzItLnR5cGVzLkJ1aWx0SW5UeXBlc01lc3NhZ2UuT3RoZXJN",
            "YXBGaWVsZEVudHJ5Eh4KFnJlcGVhdGVkX3N0cmluZ3NfZmllbGQYFCADKAkS",
            "HAoUcmVwZWF0ZWRfaW50MzJfZmllbGQYFSADKAUSGwoTcmVwZWF0ZWRfYm9v",
            "bF9maWVsZBgWIAMoCBIvCg5wa2dfZW51bV9maWVsZBgeIAEoDjIXLnR5cGVz",
            "LlBhY2thZ2VMZXZlbEVudW0SQwoObXNnX2VudW1fZmllbGQYHyABKA4yKy50",
            "eXBlcy5CdWlsdEluVHlwZXNNZXNzYWdlLk1lc3NhZ2VMZXZlbEVudW0aLwoN",
            "TWFwRmllbGRFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAU6AjgB",
            "GlAKEk90aGVyTWFwRmllbGRFbnRyeRILCgNrZXkYASABKAUSKQoFdmFsdWUY",
            "AiABKAsyGi50eXBlcy5CdWlsdEluVHlwZXNNZXNzYWdlOgI4ASIzChBNZXNz",
            "YWdlTGV2ZWxFbnVtEgkKBU1TR19BEAASCQoFTVNHX0IQARIJCgVNU0dfQxBN",
            "IswFChVXZWxsS25vd25UeXBlc01lc3NhZ2USJwoJYW55X2ZpZWxkGAEgASgL",
            "MhQuZ29vZ2xlLnByb3RvYnVmLkFueRIxCg5kdXJhdGlvbl9maWVsZBgDIAEo",
            "CzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhIrCgtlbXB0eV9maWVsZBgE",
            "IAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRItCgxzdHJ1Y3RfZmllbGQY",
            "ByABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0EjMKD3RpbWVzdGFtcF9m",
            "aWVsZBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMgoMZG91",
            "YmxlX2ZpZWxkGAogASgLMhwuZ29vZ2xlLnByb3RvYnVmLkRvdWJsZVZhbHVl",
            "EjAKC2Zsb2F0X2ZpZWxkGAsgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZsb2F0",
            "VmFsdWUSMAoLaW50NjRfZmllbGQYDCABKAsyGy5nb29nbGUucHJvdG9idWYu",
            "SW50NjRWYWx1ZRIyCgx1aW50NjRfZmllbGQYDSABKAsyHC5nb29nbGUucHJv",
            "dG9idWYuVUludDY0VmFsdWUSMAoLaW50MzJfZmllbGQYDiABKAsyGy5nb29n",
            "bGUucHJvdG9idWYuSW50MzJWYWx1ZRIyCgx1aW50MzJfZmllbGQYDyABKAsy",
            "HC5nb29nbGUucHJvdG9idWYuVUludDMyVmFsdWUSLgoKYm9vbF9maWVsZBgQ",
            "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5Cb29sVmFsdWUSMgoMc3RyaW5nX2Zp",
            "ZWxkGBEgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjAKC2J5",
            "dGVzX2ZpZWxkGBIgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkJ5dGVzVmFsdWUq",
            "MwoQUGFja2FnZUxldmVsRW51bRIJCgVQS0dfQRAAEgkKBVBLR19CEAESCQoF",
            "UEtHX0MQTWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Types.PackageLevelEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Types.BuiltInTypesMessage), global::Types.BuiltInTypesMessage.Parser, new[]{ "BytesField", "StringField", "Int32Field", "Uint32Field", "Int64Field", "Uint64Field", "BoolField", "DoubleField", "FloatField", "MapField", "OtherMapField", "RepeatedStringsField", "RepeatedInt32Field", "RepeatedBoolField", "PkgEnumField", "MsgEnumField" }, null, new[]{ typeof(global::Types.BuiltInTypesMessage.Types.MessageLevelEnum) }, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Types.WellKnownTypesMessage), global::Types.WellKnownTypesMessage.Parser, new[]{ "AnyField", "DurationField", "EmptyField", "StructField", "TimestampField", "DoubleField", "FloatField", "Int64Field", "Uint64Field", "Int32Field", "Uint32Field", "BoolField", "StringField", "BytesField" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PackageLevelEnum {
    [pbr::OriginalName("PKG_A")] PkgA = 0,
    [pbr::OriginalName("PKG_B")] PkgB = 1,
    [pbr::OriginalName("PKG_C")] PkgC = 77,
  }

  #endregion

  #region Messages
  public sealed partial class BuiltInTypesMessage : pb::IMessage<BuiltInTypesMessage> {
    private static readonly pb::MessageParser<BuiltInTypesMessage> _parser = new pb::MessageParser<BuiltInTypesMessage>(() => new BuiltInTypesMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BuiltInTypesMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Types.TypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuiltInTypesMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuiltInTypesMessage(BuiltInTypesMessage other) : this() {
      bytesField_ = other.bytesField_;
      stringField_ = other.stringField_;
      int32Field_ = other.int32Field_;
      uint32Field_ = other.uint32Field_;
      int64Field_ = other.int64Field_;
      uint64Field_ = other.uint64Field_;
      boolField_ = other.boolField_;
      doubleField_ = other.doubleField_;
      floatField_ = other.floatField_;
      mapField_ = other.mapField_.Clone();
      otherMapField_ = other.otherMapField_.Clone();
      repeatedStringsField_ = other.repeatedStringsField_.Clone();
      repeatedInt32Field_ = other.repeatedInt32Field_.Clone();
      repeatedBoolField_ = other.repeatedBoolField_.Clone();
      pkgEnumField_ = other.pkgEnumField_;
      msgEnumField_ = other.msgEnumField_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuiltInTypesMessage Clone() {
      return new BuiltInTypesMessage(this);
    }

    /// <summary>Field number for the "bytes_field" field.</summary>
    public const int BytesFieldFieldNumber = 1;
    private pb::ByteString bytesField_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString BytesField {
      get { return bytesField_; }
      set {
        bytesField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "string_field" field.</summary>
    public const int StringFieldFieldNumber = 2;
    private string stringField_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringField {
      get { return stringField_; }
      set {
        stringField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "int32_field" field.</summary>
    public const int Int32FieldFieldNumber = 3;
    private int int32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Int32Field {
      get { return int32Field_; }
      set {
        int32Field_ = value;
      }
    }

    /// <summary>Field number for the "uint32_field" field.</summary>
    public const int Uint32FieldFieldNumber = 4;
    private uint uint32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Uint32Field {
      get { return uint32Field_; }
      set {
        uint32Field_ = value;
      }
    }

    /// <summary>Field number for the "int64_field" field.</summary>
    public const int Int64FieldFieldNumber = 5;
    private long int64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Int64Field {
      get { return int64Field_; }
      set {
        int64Field_ = value;
      }
    }

    /// <summary>Field number for the "uint64_field" field.</summary>
    public const int Uint64FieldFieldNumber = 6;
    private ulong uint64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Uint64Field {
      get { return uint64Field_; }
      set {
        uint64Field_ = value;
      }
    }

    /// <summary>Field number for the "bool_field" field.</summary>
    public const int BoolFieldFieldNumber = 7;
    private bool boolField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BoolField {
      get { return boolField_; }
      set {
        boolField_ = value;
      }
    }

    /// <summary>Field number for the "double_field" field.</summary>
    public const int DoubleFieldFieldNumber = 8;
    private double doubleField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double DoubleField {
      get { return doubleField_; }
      set {
        doubleField_ = value;
      }
    }

    /// <summary>Field number for the "float_field" field.</summary>
    public const int FloatFieldFieldNumber = 9;
    private float floatField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float FloatField {
      get { return floatField_; }
      set {
        floatField_ = value;
      }
    }

    /// <summary>Field number for the "map_field" field.</summary>
    public const int MapFieldFieldNumber = 10;
    private static readonly pbc::MapField<string, int>.Codec _map_mapField_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 82);
    private readonly pbc::MapField<string, int> mapField_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, int> MapField {
      get { return mapField_; }
    }

    /// <summary>Field number for the "other_map_field" field.</summary>
    public const int OtherMapFieldFieldNumber = 12;
    private static readonly pbc::MapField<int, global::Types.BuiltInTypesMessage>.Codec _map_otherMapField_codec
        = new pbc::MapField<int, global::Types.BuiltInTypesMessage>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Types.BuiltInTypesMessage.Parser), 98);
    private readonly pbc::MapField<int, global::Types.BuiltInTypesMessage> otherMapField_ = new pbc::MapField<int, global::Types.BuiltInTypesMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Types.BuiltInTypesMessage> OtherMapField {
      get { return otherMapField_; }
    }

    /// <summary>Field number for the "repeated_strings_field" field.</summary>
    public const int RepeatedStringsFieldFieldNumber = 20;
    private static readonly pb::FieldCodec<string> _repeated_repeatedStringsField_codec
        = pb::FieldCodec.ForString(162);
    private readonly pbc::RepeatedField<string> repeatedStringsField_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> RepeatedStringsField {
      get { return repeatedStringsField_; }
    }

    /// <summary>Field number for the "repeated_int32_field" field.</summary>
    public const int RepeatedInt32FieldFieldNumber = 21;
    private static readonly pb::FieldCodec<int> _repeated_repeatedInt32Field_codec
        = pb::FieldCodec.ForInt32(170);
    private readonly pbc::RepeatedField<int> repeatedInt32Field_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> RepeatedInt32Field {
      get { return repeatedInt32Field_; }
    }

    /// <summary>Field number for the "repeated_bool_field" field.</summary>
    public const int RepeatedBoolFieldFieldNumber = 22;
    private static readonly pb::FieldCodec<bool> _repeated_repeatedBoolField_codec
        = pb::FieldCodec.ForBool(178);
    private readonly pbc::RepeatedField<bool> repeatedBoolField_ = new pbc::RepeatedField<bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<bool> RepeatedBoolField {
      get { return repeatedBoolField_; }
    }

    /// <summary>Field number for the "pkg_enum_field" field.</summary>
    public const int PkgEnumFieldFieldNumber = 30;
    private global::Types.PackageLevelEnum pkgEnumField_ = global::Types.PackageLevelEnum.PkgA;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Types.PackageLevelEnum PkgEnumField {
      get { return pkgEnumField_; }
      set {
        pkgEnumField_ = value;
      }
    }

    /// <summary>Field number for the "msg_enum_field" field.</summary>
    public const int MsgEnumFieldFieldNumber = 31;
    private global::Types.BuiltInTypesMessage.Types.MessageLevelEnum msgEnumField_ = global::Types.BuiltInTypesMessage.Types.MessageLevelEnum.MsgA;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Types.BuiltInTypesMessage.Types.MessageLevelEnum MsgEnumField {
      get { return msgEnumField_; }
      set {
        msgEnumField_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BuiltInTypesMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BuiltInTypesMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BytesField != other.BytesField) return false;
      if (StringField != other.StringField) return false;
      if (Int32Field != other.Int32Field) return false;
      if (Uint32Field != other.Uint32Field) return false;
      if (Int64Field != other.Int64Field) return false;
      if (Uint64Field != other.Uint64Field) return false;
      if (BoolField != other.BoolField) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleField, other.DoubleField)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatField, other.FloatField)) return false;
      if (!MapField.Equals(other.MapField)) return false;
      if (!OtherMapField.Equals(other.OtherMapField)) return false;
      if(!repeatedStringsField_.Equals(other.repeatedStringsField_)) return false;
      if(!repeatedInt32Field_.Equals(other.repeatedInt32Field_)) return false;
      if(!repeatedBoolField_.Equals(other.repeatedBoolField_)) return false;
      if (PkgEnumField != other.PkgEnumField) return false;
      if (MsgEnumField != other.MsgEnumField) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BytesField.Length != 0) hash ^= BytesField.GetHashCode();
      if (StringField.Length != 0) hash ^= StringField.GetHashCode();
      if (Int32Field != 0) hash ^= Int32Field.GetHashCode();
      if (Uint32Field != 0) hash ^= Uint32Field.GetHashCode();
      if (Int64Field != 0L) hash ^= Int64Field.GetHashCode();
      if (Uint64Field != 0UL) hash ^= Uint64Field.GetHashCode();
      if (BoolField != false) hash ^= BoolField.GetHashCode();
      if (DoubleField != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleField);
      if (FloatField != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatField);
      hash ^= MapField.GetHashCode();
      hash ^= OtherMapField.GetHashCode();
      hash ^= repeatedStringsField_.GetHashCode();
      hash ^= repeatedInt32Field_.GetHashCode();
      hash ^= repeatedBoolField_.GetHashCode();
      if (PkgEnumField != global::Types.PackageLevelEnum.PkgA) hash ^= PkgEnumField.GetHashCode();
      if (MsgEnumField != global::Types.BuiltInTypesMessage.Types.MessageLevelEnum.MsgA) hash ^= MsgEnumField.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BytesField.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(BytesField);
      }
      if (StringField.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StringField);
      }
      if (Int32Field != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Int32Field);
      }
      if (Uint32Field != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Uint32Field);
      }
      if (Int64Field != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Int64Field);
      }
      if (Uint64Field != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(Uint64Field);
      }
      if (BoolField != false) {
        output.WriteRawTag(56);
        output.WriteBool(BoolField);
      }
      if (DoubleField != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(DoubleField);
      }
      if (FloatField != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(FloatField);
      }
      mapField_.WriteTo(output, _map_mapField_codec);
      otherMapField_.WriteTo(output, _map_otherMapField_codec);
      repeatedStringsField_.WriteTo(output, _repeated_repeatedStringsField_codec);
      repeatedInt32Field_.WriteTo(output, _repeated_repeatedInt32Field_codec);
      repeatedBoolField_.WriteTo(output, _repeated_repeatedBoolField_codec);
      if (PkgEnumField != global::Types.PackageLevelEnum.PkgA) {
        output.WriteRawTag(240, 1);
        output.WriteEnum((int) PkgEnumField);
      }
      if (MsgEnumField != global::Types.BuiltInTypesMessage.Types.MessageLevelEnum.MsgA) {
        output.WriteRawTag(248, 1);
        output.WriteEnum((int) MsgEnumField);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BytesField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BytesField);
      }
      if (StringField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringField);
      }
      if (Int32Field != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int32Field);
      }
      if (Uint32Field != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uint32Field);
      }
      if (Int64Field != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Field);
      }
      if (Uint64Field != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uint64Field);
      }
      if (BoolField != false) {
        size += 1 + 1;
      }
      if (DoubleField != 0D) {
        size += 1 + 8;
      }
      if (FloatField != 0F) {
        size += 1 + 4;
      }
      size += mapField_.CalculateSize(_map_mapField_codec);
      size += otherMapField_.CalculateSize(_map_otherMapField_codec);
      size += repeatedStringsField_.CalculateSize(_repeated_repeatedStringsField_codec);
      size += repeatedInt32Field_.CalculateSize(_repeated_repeatedInt32Field_codec);
      size += repeatedBoolField_.CalculateSize(_repeated_repeatedBoolField_codec);
      if (PkgEnumField != global::Types.PackageLevelEnum.PkgA) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) PkgEnumField);
      }
      if (MsgEnumField != global::Types.BuiltInTypesMessage.Types.MessageLevelEnum.MsgA) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) MsgEnumField);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BuiltInTypesMessage other) {
      if (other == null) {
        return;
      }
      if (other.BytesField.Length != 0) {
        BytesField = other.BytesField;
      }
      if (other.StringField.Length != 0) {
        StringField = other.StringField;
      }
      if (other.Int32Field != 0) {
        Int32Field = other.Int32Field;
      }
      if (other.Uint32Field != 0) {
        Uint32Field = other.Uint32Field;
      }
      if (other.Int64Field != 0L) {
        Int64Field = other.Int64Field;
      }
      if (other.Uint64Field != 0UL) {
        Uint64Field = other.Uint64Field;
      }
      if (other.BoolField != false) {
        BoolField = other.BoolField;
      }
      if (other.DoubleField != 0D) {
        DoubleField = other.DoubleField;
      }
      if (other.FloatField != 0F) {
        FloatField = other.FloatField;
      }
      mapField_.Add(other.mapField_);
      otherMapField_.Add(other.otherMapField_);
      repeatedStringsField_.Add(other.repeatedStringsField_);
      repeatedInt32Field_.Add(other.repeatedInt32Field_);
      repeatedBoolField_.Add(other.repeatedBoolField_);
      if (other.PkgEnumField != global::Types.PackageLevelEnum.PkgA) {
        PkgEnumField = other.PkgEnumField;
      }
      if (other.MsgEnumField != global::Types.BuiltInTypesMessage.Types.MessageLevelEnum.MsgA) {
        MsgEnumField = other.MsgEnumField;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BytesField = input.ReadBytes();
            break;
          }
          case 18: {
            StringField = input.ReadString();
            break;
          }
          case 24: {
            Int32Field = input.ReadInt32();
            break;
          }
          case 32: {
            Uint32Field = input.ReadUInt32();
            break;
          }
          case 40: {
            Int64Field = input.ReadInt64();
            break;
          }
          case 48: {
            Uint64Field = input.ReadUInt64();
            break;
          }
          case 56: {
            BoolField = input.ReadBool();
            break;
          }
          case 65: {
            DoubleField = input.ReadDouble();
            break;
          }
          case 77: {
            FloatField = input.ReadFloat();
            break;
          }
          case 82: {
            mapField_.AddEntriesFrom(input, _map_mapField_codec);
            break;
          }
          case 98: {
            otherMapField_.AddEntriesFrom(input, _map_otherMapField_codec);
            break;
          }
          case 162: {
            repeatedStringsField_.AddEntriesFrom(input, _repeated_repeatedStringsField_codec);
            break;
          }
          case 170:
          case 168: {
            repeatedInt32Field_.AddEntriesFrom(input, _repeated_repeatedInt32Field_codec);
            break;
          }
          case 178:
          case 176: {
            repeatedBoolField_.AddEntriesFrom(input, _repeated_repeatedBoolField_codec);
            break;
          }
          case 240: {
            PkgEnumField = (global::Types.PackageLevelEnum) input.ReadEnum();
            break;
          }
          case 248: {
            MsgEnumField = (global::Types.BuiltInTypesMessage.Types.MessageLevelEnum) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the BuiltInTypesMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum MessageLevelEnum {
        [pbr::OriginalName("MSG_A")] MsgA = 0,
        [pbr::OriginalName("MSG_B")] MsgB = 1,
        [pbr::OriginalName("MSG_C")] MsgC = 77,
      }

    }
    #endregion

  }

  public sealed partial class WellKnownTypesMessage : pb::IMessage<WellKnownTypesMessage> {
    private static readonly pb::MessageParser<WellKnownTypesMessage> _parser = new pb::MessageParser<WellKnownTypesMessage>(() => new WellKnownTypesMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WellKnownTypesMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Types.TypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WellKnownTypesMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WellKnownTypesMessage(WellKnownTypesMessage other) : this() {
      anyField_ = other.anyField_ != null ? other.anyField_.Clone() : null;
      durationField_ = other.durationField_ != null ? other.durationField_.Clone() : null;
      emptyField_ = other.emptyField_ != null ? other.emptyField_.Clone() : null;
      structField_ = other.structField_ != null ? other.structField_.Clone() : null;
      timestampField_ = other.timestampField_ != null ? other.timestampField_.Clone() : null;
      DoubleField = other.DoubleField;
      FloatField = other.FloatField;
      Int64Field = other.Int64Field;
      Uint64Field = other.Uint64Field;
      Int32Field = other.Int32Field;
      Uint32Field = other.Uint32Field;
      BoolField = other.BoolField;
      StringField = other.StringField;
      BytesField = other.BytesField;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WellKnownTypesMessage Clone() {
      return new WellKnownTypesMessage(this);
    }

    /// <summary>Field number for the "any_field" field.</summary>
    public const int AnyFieldFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Any anyField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any AnyField {
      get { return anyField_; }
      set {
        anyField_ = value;
      }
    }

    /// <summary>Field number for the "duration_field" field.</summary>
    public const int DurationFieldFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Duration durationField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Duration DurationField {
      get { return durationField_; }
      set {
        durationField_ = value;
      }
    }

    /// <summary>Field number for the "empty_field" field.</summary>
    public const int EmptyFieldFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Empty emptyField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Empty EmptyField {
      get { return emptyField_; }
      set {
        emptyField_ = value;
      }
    }

    /// <summary>Field number for the "struct_field" field.</summary>
    public const int StructFieldFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Struct structField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Struct StructField {
      get { return structField_; }
      set {
        structField_ = value;
      }
    }

    /// <summary>Field number for the "timestamp_field" field.</summary>
    public const int TimestampFieldFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestampField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimestampField {
      get { return timestampField_; }
      set {
        timestampField_ = value;
      }
    }

    /// <summary>Field number for the "double_field" field.</summary>
    public const int DoubleFieldFieldNumber = 10;
    private static readonly pb::FieldCodec<double?> _single_doubleField_codec = pb::FieldCodec.ForStructWrapper<double>(82);
    private double? doubleField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double? DoubleField {
      get { return doubleField_; }
      set {
        doubleField_ = value;
      }
    }


    /// <summary>Field number for the "float_field" field.</summary>
    public const int FloatFieldFieldNumber = 11;
    private static readonly pb::FieldCodec<float?> _single_floatField_codec = pb::FieldCodec.ForStructWrapper<float>(90);
    private float? floatField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float? FloatField {
      get { return floatField_; }
      set {
        floatField_ = value;
      }
    }


    /// <summary>Field number for the "int64_field" field.</summary>
    public const int Int64FieldFieldNumber = 12;
    private static readonly pb::FieldCodec<long?> _single_int64Field_codec = pb::FieldCodec.ForStructWrapper<long>(98);
    private long? int64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long? Int64Field {
      get { return int64Field_; }
      set {
        int64Field_ = value;
      }
    }


    /// <summary>Field number for the "uint64_field" field.</summary>
    public const int Uint64FieldFieldNumber = 13;
    private static readonly pb::FieldCodec<ulong?> _single_uint64Field_codec = pb::FieldCodec.ForStructWrapper<ulong>(106);
    private ulong? uint64Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong? Uint64Field {
      get { return uint64Field_; }
      set {
        uint64Field_ = value;
      }
    }


    /// <summary>Field number for the "int32_field" field.</summary>
    public const int Int32FieldFieldNumber = 14;
    private static readonly pb::FieldCodec<int?> _single_int32Field_codec = pb::FieldCodec.ForStructWrapper<int>(114);
    private int? int32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int? Int32Field {
      get { return int32Field_; }
      set {
        int32Field_ = value;
      }
    }


    /// <summary>Field number for the "uint32_field" field.</summary>
    public const int Uint32FieldFieldNumber = 15;
    private static readonly pb::FieldCodec<uint?> _single_uint32Field_codec = pb::FieldCodec.ForStructWrapper<uint>(122);
    private uint? uint32Field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint? Uint32Field {
      get { return uint32Field_; }
      set {
        uint32Field_ = value;
      }
    }


    /// <summary>Field number for the "bool_field" field.</summary>
    public const int BoolFieldFieldNumber = 16;
    private static readonly pb::FieldCodec<bool?> _single_boolField_codec = pb::FieldCodec.ForStructWrapper<bool>(130);
    private bool? boolField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool? BoolField {
      get { return boolField_; }
      set {
        boolField_ = value;
      }
    }


    /// <summary>Field number for the "string_field" field.</summary>
    public const int StringFieldFieldNumber = 17;
    private static readonly pb::FieldCodec<string> _single_stringField_codec = pb::FieldCodec.ForClassWrapper<string>(138);
    private string stringField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringField {
      get { return stringField_; }
      set {
        stringField_ = value;
      }
    }


    /// <summary>Field number for the "bytes_field" field.</summary>
    public const int BytesFieldFieldNumber = 18;
    private static readonly pb::FieldCodec<pb::ByteString> _single_bytesField_codec = pb::FieldCodec.ForClassWrapper<pb::ByteString>(146);
    private pb::ByteString bytesField_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString BytesField {
      get { return bytesField_; }
      set {
        bytesField_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WellKnownTypesMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WellKnownTypesMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AnyField, other.AnyField)) return false;
      if (!object.Equals(DurationField, other.DurationField)) return false;
      if (!object.Equals(EmptyField, other.EmptyField)) return false;
      if (!object.Equals(StructField, other.StructField)) return false;
      if (!object.Equals(TimestampField, other.TimestampField)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.Equals(DoubleField, other.DoubleField)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(FloatField, other.FloatField)) return false;
      if (Int64Field != other.Int64Field) return false;
      if (Uint64Field != other.Uint64Field) return false;
      if (Int32Field != other.Int32Field) return false;
      if (Uint32Field != other.Uint32Field) return false;
      if (BoolField != other.BoolField) return false;
      if (StringField != other.StringField) return false;
      if (BytesField != other.BytesField) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (anyField_ != null) hash ^= AnyField.GetHashCode();
      if (durationField_ != null) hash ^= DurationField.GetHashCode();
      if (emptyField_ != null) hash ^= EmptyField.GetHashCode();
      if (structField_ != null) hash ^= StructField.GetHashCode();
      if (timestampField_ != null) hash ^= TimestampField.GetHashCode();
      if (doubleField_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.GetHashCode(DoubleField);
      if (floatField_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(FloatField);
      if (int64Field_ != null) hash ^= Int64Field.GetHashCode();
      if (uint64Field_ != null) hash ^= Uint64Field.GetHashCode();
      if (int32Field_ != null) hash ^= Int32Field.GetHashCode();
      if (uint32Field_ != null) hash ^= Uint32Field.GetHashCode();
      if (boolField_ != null) hash ^= BoolField.GetHashCode();
      if (stringField_ != null) hash ^= StringField.GetHashCode();
      if (bytesField_ != null) hash ^= BytesField.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (anyField_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AnyField);
      }
      if (durationField_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DurationField);
      }
      if (emptyField_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(EmptyField);
      }
      if (structField_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(StructField);
      }
      if (timestampField_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(TimestampField);
      }
      if (doubleField_ != null) {
        _single_doubleField_codec.WriteTagAndValue(output, DoubleField);
      }
      if (floatField_ != null) {
        _single_floatField_codec.WriteTagAndValue(output, FloatField);
      }
      if (int64Field_ != null) {
        _single_int64Field_codec.WriteTagAndValue(output, Int64Field);
      }
      if (uint64Field_ != null) {
        _single_uint64Field_codec.WriteTagAndValue(output, Uint64Field);
      }
      if (int32Field_ != null) {
        _single_int32Field_codec.WriteTagAndValue(output, Int32Field);
      }
      if (uint32Field_ != null) {
        _single_uint32Field_codec.WriteTagAndValue(output, Uint32Field);
      }
      if (boolField_ != null) {
        _single_boolField_codec.WriteTagAndValue(output, BoolField);
      }
      if (stringField_ != null) {
        _single_stringField_codec.WriteTagAndValue(output, StringField);
      }
      if (bytesField_ != null) {
        _single_bytesField_codec.WriteTagAndValue(output, BytesField);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (anyField_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnyField);
      }
      if (durationField_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DurationField);
      }
      if (emptyField_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EmptyField);
      }
      if (structField_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StructField);
      }
      if (timestampField_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimestampField);
      }
      if (doubleField_ != null) {
        size += _single_doubleField_codec.CalculateSizeWithTag(DoubleField);
      }
      if (floatField_ != null) {
        size += _single_floatField_codec.CalculateSizeWithTag(FloatField);
      }
      if (int64Field_ != null) {
        size += _single_int64Field_codec.CalculateSizeWithTag(Int64Field);
      }
      if (uint64Field_ != null) {
        size += _single_uint64Field_codec.CalculateSizeWithTag(Uint64Field);
      }
      if (int32Field_ != null) {
        size += _single_int32Field_codec.CalculateSizeWithTag(Int32Field);
      }
      if (uint32Field_ != null) {
        size += _single_uint32Field_codec.CalculateSizeWithTag(Uint32Field);
      }
      if (boolField_ != null) {
        size += _single_boolField_codec.CalculateSizeWithTag(BoolField);
      }
      if (stringField_ != null) {
        size += _single_stringField_codec.CalculateSizeWithTag(StringField);
      }
      if (bytesField_ != null) {
        size += _single_bytesField_codec.CalculateSizeWithTag(BytesField);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WellKnownTypesMessage other) {
      if (other == null) {
        return;
      }
      if (other.anyField_ != null) {
        if (anyField_ == null) {
          AnyField = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        AnyField.MergeFrom(other.AnyField);
      }
      if (other.durationField_ != null) {
        if (durationField_ == null) {
          DurationField = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        DurationField.MergeFrom(other.DurationField);
      }
      if (other.emptyField_ != null) {
        if (emptyField_ == null) {
          EmptyField = new global::Google.Protobuf.WellKnownTypes.Empty();
        }
        EmptyField.MergeFrom(other.EmptyField);
      }
      if (other.structField_ != null) {
        if (structField_ == null) {
          StructField = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        StructField.MergeFrom(other.StructField);
      }
      if (other.timestampField_ != null) {
        if (timestampField_ == null) {
          TimestampField = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimestampField.MergeFrom(other.TimestampField);
      }
      if (other.doubleField_ != null) {
        if (doubleField_ == null || other.DoubleField != 0D) {
          DoubleField = other.DoubleField;
        }
      }
      if (other.floatField_ != null) {
        if (floatField_ == null || other.FloatField != 0F) {
          FloatField = other.FloatField;
        }
      }
      if (other.int64Field_ != null) {
        if (int64Field_ == null || other.Int64Field != 0L) {
          Int64Field = other.Int64Field;
        }
      }
      if (other.uint64Field_ != null) {
        if (uint64Field_ == null || other.Uint64Field != 0UL) {
          Uint64Field = other.Uint64Field;
        }
      }
      if (other.int32Field_ != null) {
        if (int32Field_ == null || other.Int32Field != 0) {
          Int32Field = other.Int32Field;
        }
      }
      if (other.uint32Field_ != null) {
        if (uint32Field_ == null || other.Uint32Field != 0) {
          Uint32Field = other.Uint32Field;
        }
      }
      if (other.boolField_ != null) {
        if (boolField_ == null || other.BoolField != false) {
          BoolField = other.BoolField;
        }
      }
      if (other.stringField_ != null) {
        if (stringField_ == null || other.StringField != "") {
          StringField = other.StringField;
        }
      }
      if (other.bytesField_ != null) {
        if (bytesField_ == null || other.BytesField != pb::ByteString.Empty) {
          BytesField = other.BytesField;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (anyField_ == null) {
              AnyField = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(AnyField);
            break;
          }
          case 26: {
            if (durationField_ == null) {
              DurationField = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(DurationField);
            break;
          }
          case 34: {
            if (emptyField_ == null) {
              EmptyField = new global::Google.Protobuf.WellKnownTypes.Empty();
            }
            input.ReadMessage(EmptyField);
            break;
          }
          case 58: {
            if (structField_ == null) {
              StructField = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(StructField);
            break;
          }
          case 66: {
            if (timestampField_ == null) {
              TimestampField = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampField);
            break;
          }
          case 82: {
            double? value = _single_doubleField_codec.Read(input);
            if (doubleField_ == null || value != 0D) {
              DoubleField = value;
            }
            break;
          }
          case 90: {
            float? value = _single_floatField_codec.Read(input);
            if (floatField_ == null || value != 0F) {
              FloatField = value;
            }
            break;
          }
          case 98: {
            long? value = _single_int64Field_codec.Read(input);
            if (int64Field_ == null || value != 0L) {
              Int64Field = value;
            }
            break;
          }
          case 106: {
            ulong? value = _single_uint64Field_codec.Read(input);
            if (uint64Field_ == null || value != 0UL) {
              Uint64Field = value;
            }
            break;
          }
          case 114: {
            int? value = _single_int32Field_codec.Read(input);
            if (int32Field_ == null || value != 0) {
              Int32Field = value;
            }
            break;
          }
          case 122: {
            uint? value = _single_uint32Field_codec.Read(input);
            if (uint32Field_ == null || value != 0) {
              Uint32Field = value;
            }
            break;
          }
          case 130: {
            bool? value = _single_boolField_codec.Read(input);
            if (boolField_ == null || value != false) {
              BoolField = value;
            }
            break;
          }
          case 138: {
            string value = _single_stringField_codec.Read(input);
            if (stringField_ == null || value != "") {
              StringField = value;
            }
            break;
          }
          case 146: {
            pb::ByteString value = _single_bytesField_codec.Read(input);
            if (bytesField_ == null || value != pb::ByteString.Empty) {
              BytesField = value;
            }
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
