// <auto-generated>
//     Generated by the protocol buffer compiler plugin.  DO NOT EDIT!
//     source: greeter.proto
// </auto-generated>


using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace Example
{

    /// <summary>
    /// This is just an example service that
    /// uses imports
    /// </summary>
    public class GreeterHttpClient
    {
        private readonly HttpClient _client;


        public GreeterHttpClient(HttpClient client)
        {
            client.DefaultRequestHeaders.Add("Accept", "application/protobuf");
            _client = client;
        }


		
        /// <summary>
        /// Simple hello method
        /// </summary>
        public async Task<global::Example.HelloResponse> Hello(global::Example.HelloRequest request)
        {
            return await DoRequest(request, "example.Greeter/Hello", global::Example.HelloResponse.Parser);
        }
		


        /// <summary>
        /// Simple ext method
        /// </summary>
        [Obsolete] public async Task<global::Ext.ExtResponse> Ext(global::Ext.ExtRequest request)
        {
            return await DoRequest(request, "example.Greeter/Ext", global::Ext.ExtResponse.Parser);
        }
		


        /// <summary>

        /// </summary>
        public async Task<global::Zett.ZettResponse> Zett(global::Zett.ZettRequest request)
        {
            return await DoRequest(request, "example.Greeter/Zett", global::Zett.ZettResponse.Parser);
        }
		


        private async Task<T> DoRequest<T>(IMessage request, string uri, MessageParser<T> responseParser)
            where T : IMessage<T>
        {
            var requestMessage = new HttpRequestMessage(HttpMethod.Put, uri);
            requestMessage.Content = new ByteArrayContent(request.ToByteArray());
            requestMessage.Content.Headers.ContentType =
                MediaTypeHeaderValue.Parse($"application/protobuf; proto={request.Descriptor.FullName}");
            var response = await _client.SendAsync(requestMessage);
            response.EnsureSuccessStatusCode();
            var responseStream = await response.Content.ReadAsStreamAsync();
            return responseParser.ParseFrom(responseStream);
        }



    }
}
