<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nested-user.proto

namespace GPBMetadata;

class NestedUser
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Nested::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84010a116e65737465642d757365722e70726f746f120b6e6573746564" .
            "5f75736572225a0a0a4e657374656455736572121f0a026e6f1801200128" .
            "0b32132e6e65737465642e4e65737465644f75746572122b0a026e691802" .
            "2001280b321f2e6e65737465642e4e65737465644f757465722e4e657374" .
            "6564496e6e6572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

