<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nested.proto

namespace GPBMetadata;

class Nested
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a94010a0c6e65737465642e70726f746f12066e657374656422740a0b4e" .
            "65737465644f7574657212120a0a6f757465725f6e616d65180120012809" .
            "122e0a05696e6e657218022001280b321f2e6e65737465642e4e65737465" .
            "644f757465722e4e6573746564496e6e65721a210a0b4e6573746564496e" .
            "6e657212120a0a696e6e65725f6e616d65180120012809620670726f746f" .
            "33"
        ), true);

        static::$is_initialized = true;
    }
}

